# Generated by Django 2.2.3 on 2019-07-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cavoke_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ('createdOn', 'player_uid', 'game_type_id', 'game_session_id')},
        ),
    ]
