# Generated by Django 2.2.3 on 2019-07-15 10:06

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cavoke_app', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ('createdOn', 'player_uid', 'game_type_id', 'game_session_id', 'expiresOn')},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='expiresOn',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 10, 5, 14, 485551, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='firstActionOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gamesMadeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='gamesMadeMaxCount',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastGameCreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 10, 5, 39, 658205, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lastPlayedOn',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 10, 5, 46, 674941, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_session_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
