# Generated by Django 2.2.3 on 2019-07-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavoke_app', '0004_auto_20190715_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(max_length=100),
        ),
    ]
