# Generated by Django 2.2.3 on 2019-07-15 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cavoke_app', '0006_remove_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firstActionOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastGameCreatedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastPlayedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
