# Generated by Django 2.2.4 on 2019-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavoke_app', '0009_gametype_creator_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='game_object_bytes',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gametype',
            name='type_module_bytes',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
